# file: clifford/inverse/fls.py
"""
Faddeev-LeVerrier-Souriau (FLS) multivector inverse for Euclidean Cl(n,0).

Covers dimensions 6-13.  Each dimension uses a specific involution
(a composite of reversion and a Thue-Morse block pattern) that makes
C = A * involution(A) self-reverse.  A short polynomial iteration on C
then produces a near-scalar result whose scalar part is the determinant.

Involution structure
--------------------
The involution applied to A before forming C = A * involute(A) is:

    involution[n] = reversion_sign(n) * fix[n]

where reversion_sign(n) = [+1,+1,-1,-1][grade(n) mod 4] and fix[] is a
Thue-Morse block pattern that compensates for the extra pseudoscalar/scalar
mixing that appears above 6D.

fix[] is generated by _involution_fix(dim):
  - block_size = 2^dim / num_blocks
  - num_blocks = 2^((dim-5)//2)       (1,2,2,4,4,8,8,16 for dims 6-13)
  - sign of block n = (-1)^popcount(n)  (Thue-Morse)

Tweak coefficients
------------------
The FLS polynomial iteration requires rational scalar rescalings at each
step.  For dimension d the coefficients are

    tweak[k] = (N - k) / k,   k = 1 .. N-1,   N = 2^(d//2 - 1)

Both even and odd dimensions in the same pair (6&7, 8&9, …) share the
same tweak array and the same N.

Numerical precision
-------------------
At dimensions 12-13 the 31-step polynomial accumulates enough floating-
point error to leave residuals of O(1e-3) to O(1e-2).  Follow with
Newton-Schulz refinement (clifford.inverse.newton) to recover full
double precision.

References
----------
Jones, D. A. — notebooks/Model Inverses.ipynb, 2026.
"""

import numpy as np
import clifford.context as Clif
from clifford.multivector import Accum
from clifford.util import inverse_involution  # noqa: F401 — re-exported from here


def _make_tweak(dim: int) -> list:
    """Rational rescaling coefficients for the FLS iteration.

    Returns [(N-k)/k for k in 1..N-1] where N = 2^(dim//2 - 1).
    Dims (2m) and (2m+1) share the same tweak array.
    """
    N = 1 << (dim // 2 - 1)
    return [(N - k) / k for k in range(1, N)]


# ---------------------------------------------------------------------------
# FLS inverse — operates on Reg arrays directly for speed
# ---------------------------------------------------------------------------

def even_inverse(A: Accum) -> Accum:
    """FLS inverse for even Euclidean dimensions (6, 8, 10, 12).

    Parameters
    ----------
    A : Accum
        Non-singular multivector in Cl(dim, 0), dim in {6, 8, 10, 12}.

    Returns
    -------
    Accum
        Approximate inverse.  At dim <= 10 residuals are < 1e-8;
        at dim 12 follow with newton_schulz() for full precision.
    """
    mul = Clif._ActiveTable.fast_mul
    T   = _make_tweak(A.dimensions)
    inv = inverse_involution(A.dimensions)

    b = inv * A.Reg           # involute(A) coefficient array
    c = mul(A.Reg, b)         # C = A * involute(A)
    d = c.copy()
    d[0] *= -T[0]
    for i in range(1, len(T)):
        d    = mul(d, c)
        d[0] *= -T[i]
    e  = mul(d, c)
    rc = (1.0 / e[0]) * d
    ra = mul(b, rc)

    result     = Accum()
    result.Reg = ra
    return result


def odd_inverse(A: Accum) -> Accum:
    """FLS inverse for odd Euclidean dimensions (7, 9, 11, 13).

    The odd case carries scalar and pseudoscalar components through the
    iteration together; the pseudoscalar slot is tweaked in parallel with
    the scalar slot at each step.

    Parameters
    ----------
    A : Accum
        Non-singular multivector in Cl(dim, 0), dim in {7, 9, 11, 13}.

    Returns
    -------
    Accum
        Approximate inverse.  At dim <= 11 residuals are < 1e-8;
        at dim 13 follow with newton_schulz() for full precision.
    """
    dim    = A.dimensions
    PSEUDO = (1 << dim) - 1
    mul    = Clif._ActiveTable.fast_mul
    T      = _make_tweak(dim)
    inv    = inverse_involution(dim)

    b = inv * A.Reg
    c = mul(A.Reg, b)
    d = c.copy()
    d[0]      *= -T[0]
    d[PSEUDO] *= -T[0]
    for i in range(1, len(T)):
        d         = mul(d, c)
        d[0]      *= -T[i]
        d[PSEUDO] *= -T[i]
    e        = mul(d, c)
    ep       = e.copy()
    ep[PSEUDO] *= -1.0
    epe      = mul(ep, e)
    rc       = (1.0 / epe[0]) * mul(ep, d)
    ra       = mul(b, rc)

    result     = Accum()
    result.Reg = ra
    return result


def fls_inverse(A: Accum) -> Accum:
    """FLS inverse for Euclidean Cl(dim, 0), dim in 6-13.

    Dispatches to even_inverse or odd_inverse based on dimension.
    For dims 12-13, compose with newton_schulz() from clifford.inverse.newton
    to recover full double precision.

    Parameters
    ----------
    A : Accum
        Non-singular multivector.

    Returns
    -------
    Accum
        Multiplicative inverse of A.

    Raises
    ------
    ValueError
        If dimension is outside 6-13.
    """
    dim = A.dimensions
    if dim < 6 or dim > 13:
        raise ValueError(f"fls_inverse supports dimensions 6-13; got {dim}")
    return even_inverse(A) if dim % 2 == 0 else odd_inverse(A)
