# file: clifford/inverse/jones.py
"""
The Jones multivector inverse.

This module provides a closed-form inverse for non-singular multivectors in
Clifford algebras of dimension ≤ 6, derived from the structure of
``B = A * ~A``.

Background
----------
For a multivector *A* in ``Cl(p, q, r)`` with ``d = p + q + r ≤ 6``,
the product ``B = A * ~A`` is self-reverse (``~B = B``) and contains only
grades ``{0, 1, 4, 5}`` (for 5D or 6D).  Crucially, *B* can be reduced
to a scalar through a small number of further multiplications with grade-
selective sign changes, without knowing anything about the grade structure
of *A* itself.

The number of multivector multiplications required is:

==========  ===============================
Dimensions  Multiplications
==========  ===============================
≤ 4         3  (A*~A, copy+negate, × B)
5 or 6      5  (A*~A, ×B, ×B, ×B, × ~A)
==========  ===============================

This compares favourably with the Shirokov algorithm (7 multiplications
for 6D, 15 for 7D).

Numba strategy
--------------
The computational kernel operates entirely on raw NumPy arrays and is
compiled with Numba's ``@njit``.  The Python wrapper :func:`jones_inverse`
extracts ``.Reg``, calls the kernel once, then performs a post-hoc
finiteness check on the result to detect singular inputs.  This single-pass
design avoids the cost of a separate pre-check and keeps Jones competitive
with Shirokov.

The kernel is generated by a factory function :func:`_make_jones_kernel`
that closes over the active sign-table multiplier, and cached between calls
so that Numba JIT compilation overhead is paid only once per algebra
configuration.

Performance (6D, Chromebook, Numba 0.65)
-----------------------------------------
- Jones (single pass):  ~32 µs  (5 multivector multiplications)
- Shirokov:             ~37 µs  (7 multivector multiplications)

References
----------
Jones, D. A. — unpublished research notes, 2025–2026.
Original public-package version in ``archive/jones_6D_inverse.py``.
"""

import numpy as np
from numba import njit

import clifford.context as Clif
from clifford.multivector import Accum


def _make_jones_kernel(fast_mul):
    """Factory that closes a Numba kernel over the active multiplier.

    Parameters
    ----------
    fast_mul : callable
        Numba-jitted ``(u_reg, v_reg) -> result_reg`` from the active
        :class:`~clifford.sign_table.SignTable`.

    Returns
    -------
    callable
        A ``@njit``-compiled function
        ``_kernel(a_reg, rev_a_reg, n) -> inv_reg`` implementing the Jones
        iteration on raw NumPy arrays.
    """
    @njit
    def _kernel(a_reg: np.ndarray, rev_a_reg: np.ndarray, n: int) -> np.ndarray:
        """Jones inverse core (operates on raw coefficient arrays).

        Parameters
        ----------
        a_reg : numpy.ndarray
            Coefficient array of *A*.
        rev_a_reg : numpy.ndarray
            Coefficient array of ``~A`` (the reverse of *A*).
        n : int
            Algebra dimension (must be ≤ 6).

        Returns
        -------
        numpy.ndarray
            Coefficient array of the inverse of *A*.
            Contains ``inf`` or ``nan`` if *A* is singular.
        """
        b_reg = fast_mul(a_reg, rev_a_reg)   # B = A * ~A

        if n <= 2:
            denom    = b_reg[0]
            g_reg    = np.zeros_like(b_reg)
            g_reg[0] = 1.0
        elif n <= 4:
            g_reg    = b_reg.copy()
            g_reg[0] *= -1.0
            d_reg    = fast_mul(g_reg, b_reg)
            denom    = d_reg[0]
        else:
            # n == 5 or 6
            g_reg    = b_reg.copy()
            g_reg[0] *= -3.0
            g_reg    = fast_mul(g_reg, b_reg)
            g_reg[0] *= -1.0
            g_reg    = fast_mul(g_reg, b_reg)
            g_reg[0] *= (-1.0 / 3.0)
            i_reg    = g_reg.copy()            # adjugate of B
            g_reg    = fast_mul(g_reg, b_reg)  # now scalar
            denom    = g_reg[0]
            g_reg    = i_reg                   # restore for return path

        inv_b_reg = g_reg * (1.0 / denom)     # singular → inf
        return fast_mul(rev_a_reg, inv_b_reg)

    return _kernel


# ---------------------------------------------------------------------------
# Module-level kernel cache
# ---------------------------------------------------------------------------

_cached_kernel   = None
_cached_table_id = None


def _get_kernel():
    """Return (or build and cache) the Jones kernel for the current algebra."""
    global _cached_kernel, _cached_table_id
    table = Clif._ActiveTable
    if table is None or table.fast_mul is None:
        raise NotImplementedError(
            "jones_inverse requires an active Numba-compatible sign table "
            "(dimensions < 8)."
        )
    table_id = id(table)
    if table_id != _cached_table_id:
        _cached_kernel   = _make_jones_kernel(table.fast_mul)
        _cached_table_id = table_id
    return _cached_kernel


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def jones_inverse(A: Accum) -> Accum:
    """Compute the multiplicative inverse of *A* using the Jones algorithm.

    Valid for non-singular multivectors in algebras of dimension ≤ 6.
    Uses a single kernel pass followed by a finiteness check to detect
    singular inputs without the overhead of a separate pre-check.

    Parameters
    ----------
    A : Accum
        A non-singular multivector in the current algebra.

    Returns
    -------
    Accum
        The multiplicative inverse of *A*, satisfying
        ``jones_inverse(A) * A ≈ 1``.

    Raises
    ------
    ValueError
        If *A* is singular (result contains non-finite values), or if
        the algebra dimension exceeds 6.
    NotImplementedError
        If no active Numba-compatible sign table is available.

    Examples
    --------
    ::

        import clifford.context as Clif
        import clifford.util as util
        from clifford.inverse.jones import jones_inverse

        Clif.Cl(6)
        A = util.random(signature=0, dimensions=6)
        I = jones_inverse(A)
        print(I * A)    # 00000000         1.00000000

    Notes
    -----
    Cost: 3 multivector multiplications for ``d ≤ 4``;
    5 multiplications for ``d ∈ {5, 6}``.

    For ``d ≥ 7`` use :func:`clifford.inverse.shirokov.shirokov_inverse`.
    """
    n = A.dimensions
    if n > 6:
        raise ValueError(
            f"jones_inverse is limited to dimensions ≤ 6; "
            f"this multivector has dimension {n}. "
            f"Use clifford.inverse.shirokov.shirokov_inverse instead."
        )

    kernel     = _get_kernel()
    result     = Accum()
    result.Reg = kernel(A.Reg, (~A).Reg, n)

    if not np.isfinite(result.Reg).all():
        raise ValueError(
            "jones_inverse: multivector is singular "
            "(scalar denominator is zero)."
        )

    return result